name: Release

on:
  push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: GoReleaser snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          # --snapshot tells GoReleaser to skip tag checks
          # and treat the current commit as a snapshot version
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
